### ISSUE TITLE
Versioning issue with WDC Simulator

### ISSUE THREAD

**Issue by espressobeanies** [tableau/webdataconnector#282]
Hi,

When I go to run install and run the WDC Simulator per the [instructions](http://tableau.github.io/webdataconnector/docs/), I get the following error outputs after executing **`npm start`**:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
2 info using npm@3.5.2
3 info using node@v4.2.6
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle webdataconnector@2.0.0~prestart: webdataconnector@2.0.0
6 silly lifecycle webdataconnector@2.0.0~prestart: no script for prestart, continuing
7 info lifecycle webdataconnector@2.0.0~start: webdataconnector@2.0.0
8 verbose lifecycle webdataconnector@2.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle webdataconnector@2.0.0~start: PATH: /usr/share/npm/bin/node-gyp-bin:/home/local__admin/webdataconnector/node_modules/.bin:/root/bin:/root/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
10 verbose lifecycle webdataconnector@2.0.0~start: CWD: /home/local__admin/webdataconnector
11 silly lifecycle webdataconnector@2.0.0~start: Args: [ '-c',
11 silly lifecycle   'node node_modules/npm-run-all/bin/npm-run-all --parallel corsproxy http-server' ]
12 info lifecycle webdataconnector@2.0.0~start: Failed to exec start script
13 verbose stack Error: webdataconnector@2.0.0 start: `node node_modules/npm-run-all/bin/npm-run-all --parallel corsproxy http-server`
13 verbose stack spawn ENOENT
13 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:17:16)
13 verbose stack     at emitTwo (events.js:87:13)
13 verbose stack     at ChildProcess.emit (events.js:172:7)
13 verbose stack     at maybeClose (internal/child_process.js:821:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
14 verbose pkgid webdataconnector@2.0.0
15 verbose cwd /home/local__admin/webdataconnector
16 error Linux 4.4.0-87-generic
17 error argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
18 error node v4.2.6
19 error npm  v3.5.2
20 error file sh
21 error code ELIFECYCLE
22 error errno ENOENT
23 error syscall spawn
24 error webdataconnector@2.0.0 start: `node node_modules/npm-run-all/bin/npm-run-all --parallel corsproxy http-server`
24 error spawn ENOENT
25 error Failed at the webdataconnector@2.0.0 start script 'node node_modules/npm-run-all/bin/npm-run-all --parallel corsproxy http-server'.
25 error Make sure you have the latest version of node.js and npm installed.
25 error If you do, this is most likely a problem with the webdataconnector package,
25 error not with npm itself.
25 error Tell the author that this fails on your system:
25 error     node node_modules/npm-run-all/bin/npm-run-all --parallel corsproxy http-server
25 error You can get information on how to open an issue for this project with:
25 error     npm bugs webdataconnector
25 error Or if that isn't available, you can get their info via:
25 error     npm owner ls webdataconnector
25 error There is likely additional logging output above.
26 verbose exit [ 1, true ]
```
Is the WDC Simulator being kept up-to-date or is there something on my end I just need to do? I tried this in a Docker container and on my local machine getting the same error back in both instances and I also tried running **`npm update -g`** in the Git folder that was downloaded onto my machine.

**Comment by chenteng2016** [comment]
@espressobeanies would you please consider upgrading your node version to >=v10?

**Comment by chenteng2016** [comment]
Please help reopen if there is still an issue, thanks for contributing to webdataconnector!
