### ISSUE TITLE
Simulator dependency install failing with error "Failed at the ejs@2.7.4 postinstall script"

### ISSUE THREAD

**Issue by nmadhok** [tableau/webdataconnector#368]
Cloned the repository and tried to install Simulator following instructions from https://tableau.github.io/webdataconnector/docs/#run-the-simulator but install fails with the error below:

```
root@server:~# git clone https://github.com/tableau/webdataconnector.git
Cloning into 'webdataconnector'...
remote: Enumerating objects: 18, done.
remote: Counting objects: 100% (18/18), done.
remote: Compressing objects: 100% (18/18), done.
remote: Total 3090 (delta 9), reused 1 (delta 0), pack-reused 3072
Receiving objects: 100% (3090/3090), 8.53 MiB | 0 bytes/s, done.
Resolving deltas: 100% (1785/1785), done.
root@server:~# cd webdataconnector/
root@server:~/webdataconnector# ls
assets     _config.yml  Examples  _includes   _layouts  news          _posts     Simulator
community  docs         Gemfile   index.html  LICENSE   package.json  README.md  webpack.config.js
```

`npm install --production` failing with the following error message:
```
root@server:~/webdataconnector# npm install --production
 ejs@2.7.4 postinstall /root/webdataconnector/node_modules/ejs
> node ./postinstall.js

internal/modules/cjs/loader.js:965
  throw err;
  ^

Error: Cannot find module '/root/webdataconnector/node_modules/ejs/postinstall.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:962:15)
    at Function.Module._load (internal/modules/cjs/loader.js:838:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN eslint-config-airbnb@9.0.1 requires a peer of eslint@^2.9.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-import@1.16.0 requires a peer of eslint@2.x - 3.x but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-jsx-a11y@1.5.5 requires a peer of eslint@^2.10.2 || 3.x but none is installed. You must install peer dependencies yourself.
npm WARN ajv-keywords@2.1.1 requires a peer of ajv@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-airbnb-base@3.0.1 requires a peer of eslint@^2.9.0 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ejs@2.7.4 postinstall: `node ./postinstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ejs@2.7.4 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-05-07T22_40_49_495Z-debug.log
```

**Node version:** `v13.14.0`

**npm version:** `6.14.4`

**Comment by chenteng2016** [comment]
@nmadhok thanks for contributing to webdataconnector!
In the latest master, we didn't find the ejs as dependency, could you please pull the latest master and see if it works for you?
Another note is please make sure you are referencing the registry you would like to utilize, for instance, http://registry.npmjs.org/, you could use 'npm config set registry <registry>' to set and 'npm config get registry' to check.

**Comment by chenteng2016** [comment]
Please help reopen if there is still an issue. Thanks for contributing to webdataconnector!
