### ISSUE TITLE
hapi dependency error

### ISSUE THREAD

**Issue by MsJKrdck** [tableau/webdataconnector#389]
After cloning the repository and executing npm install the wdc simulator is failing to start with the following error:

`webdataconnector/node_modules/hapi/lib/defaults.js:49
            uploads: Os.tmpDir(),
                        ^

TypeError: Os.tmpDir is not a function
    at Object.<anonymous> (/Users/jules/Documents/dev/tes/webdataconnector/node_modules/hapi/lib/defaults.js:49:25)
    at Module._compile (internal/modules/cjs/loader.js:1185:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1205:10)
    at Module.load (internal/modules/cjs/loader.js:1034:32)
    at Function.Module._load (internal/modules/cjs/loader.js:923:14)
    at Module.require (internal/modules/cjs/loader.js:1074:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/jules/Documents/dev/tes/webdataconnector/node_modules/hapi/lib/route.js:9:16)
    at Module._compile (internal/modules/cjs/loader.js:1185:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1205:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! webdataconnector@2.0.0 corsproxy: export CORSPROXY_PORT=8889 || set CORSPROXY_PORT=8889 && node node_modules/corsproxy/bin/corsproxy
npm ERR! Exit status 1
npm ERR!`

The workaround is correcting the row in the hapi dependecy file manually with: `uploads: Os.tmpdir()`

Please fix this dependency! Thanks.

**Comment by KeshiaRose** [comment]
Hi @MsJKrdck, please use `npm run http-server` to run the Simulator instead. This seems to be an issue cropping up with the newest versions of node and I'm not sure if/when we will fix it.
-Keshia

**Comment by markerikson** [comment]
A coworker just ran into this, and it seems that the WDC setup instructions might need to be updated to reflect this issue - they just say to run `npm start`. Would be helpful to have a pointer to this in case others run into it.
