### ISSUE TITLE
npm start: Cannot find module corsproxy

### ISSUE THREAD

**Issue by xiumingliu** [tableau/webdataconnector#425]
Hello, 

I am trying to follow the "Get Started" doc: https://tableau.github.io/webdataconnector/docs/index.html 

At the second step of starting the test web server, I run "npm start" command. And I get the following error (the full message is attached in the end): 
Error: Cannot find module '...\webdataconnector\node_modules\corsproxy\bin\corsproxy'

I check the "\webdataconnector\node_modules\" folder and the corsproxy is indeed missing. How do I add this module for WDC? 

OS: Windows 10
node version: v14.15.3
npm version: 6.14.9

Thank you!

Attached is the full error message:

...\webdataconnector>npm start

> webdataconnector@2.0.0 start J:\My Documents\Github\webdataconnector
> node node_modules/npm-run-all/bin/npm-run-all --parallel corsproxy http-server

> webdataconnector@2.0.0 corsproxy J:\My Documents\Github\webdataconnector
> export CORSPROXY_PORT=8889 || set CORSPROXY_PORT=8889 && node node_modules/corsproxy/bin/corsproxy

'export' is not recognized as an internal or external command,
operable program or batch file.

> webdataconnector@2.0.0 http-server J:\My Documents\Github\webdataconnector
> node node_modules/http-server/bin/http-server -p 8888 -c-1

internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'J:\My Documents\Github\webdataconnector\node_modules\corsproxy\bin\corsproxy'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! webdataconnector@2.0.0 corsproxy: `export CORSPROXY_PORT=8889 || set CORSPROXY_PORT=8889 && node node_modules/corsproxy/bin/corsproxy`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the webdataconnector@2.0.0 corsproxy script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     ...\npm-cache\_logs\2021-01-04T10_40_42_268Z-debug.log
ERROR: "corsproxy" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! webdataconnector@2.0.0 start: `node node_modules/npm-run-all/bin/npm-run-all --parallel corsproxy http-server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the webdataconnector@2.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!    ...\npm-cache\_logs\2021-01-04T10_40_42_475Z-debug.log

**Comment by xiumingliu** [comment]
Hi 

Found a solution myself. 

1. Install the "npm-install-missing" package: https://www.npmjs.com/package/npm-install-missing
2. Run npm-install-missing under the WDC folder

...\webdataconnector>npm-install-missing
Package      Current  Wanted  Latest  Location
corsproxy    MISSING   1.5.0   1.5.0  webdataconnector
http-server    0.9.0   0.9.0  0.12.3  webdataconnector
npm-run-all    2.3.0   2.3.0   4.1.5  webdataconnector
[ [ 'corsproxy', '1.5.0' ] ]

> ejs@2.7.4 postinstall ...\webdataconnector\node_modules\ejs
> node ./postinstall.js

Thank you for installing EJS: built with the Jake JavaScript build tool (https://jakejs.com/)

npm notice created a lockfile as package-lock.json. You should commit this file.
+ corsproxy@1.5.0
added 2 packages from 2 contributors in 2.852s

17 packages are looking for funding
  run `npm fund` for details

npm-install-missing: Successfully installed: corsproxy@1.5.0
