### ISSUE TITLE
npm install -g @tableau/taco-toolkit not work

### ISSUE THREAD

**Issue by duniang818** [tableau/webdataconnector#528]
npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
npm WARN cleanup Failed to remove some directories [
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\xiaokeai\\AppData\\Roaming\\npm\\node_modules\\@tableau\\taco-toolkit\\node_modules\\libxmljs2',
npm WARN cleanup     [Error: EBUSY: resource busy or locked, rmdir 'C:\Users\xiaokeai\AppData\Roaming\npm\node_modules\@tableau\taco-toolkit\node_modules\libxmljs2'] {
npm WARN cleanup       errno: -4082,
npm WARN cleanup       code: 'EBUSY',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Users\\xiaokeai\\AppData\\Roaming\\npm\\node_modules\\@tableau\\taco-toolkit\\node_modules\\libxmljs2'
npm WARN cleanup     }
npm WARN cleanup   ],
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\xiaokeai\\AppData\\Roaming\\npm\\node_modules\\@tableau\\taco-toolkit',
npm WARN cleanup     [Error: EPERM: operation not permitted, rmdir 'C:\Users\xiaokeai\AppData\Roaming\npm\node_modules\@tableau\taco-toolkit\node_modules\duckdb\src\duckdb\src\include'] {
npm WARN cleanup       errno: -4048,
npm WARN cleanup       code: 'EPERM',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Users\\xiaokeai\\AppData\\Roaming\\npm\\node_modules\\@tableau\\taco-toolkit\\node_modules\\duckdb\\src\\duckdb\\src\\include'
npm WARN cleanup     }
npm WARN cleanup   ]
npm WARN cleanup ]
npm ERR! code 1
npm ERR! path C:\Users\xiaokeai\AppData\Roaming\npm\node_modules\@tableau\taco-toolkit\node_modules\isolated-vm
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c prebuild-install || (node-gyp rebuild --release -j 4 && node-gyp clean)
npm ERR! prebuild-install warn install connect ETIMEDOUT 185.199.110.133:443
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.4.0
npm ERR! gyp info using node@18.19.0 | win32 | x64
npm ERR! gyp info find Python using Python version 3.12.1 found at "C:\Python312\python.exe"
npm ERR! gyp info find VS using VS2019 (16.11.33920.266) found at:
npm ERR! gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools"
npm ERR! gyp info find VS run with --verbose for detailed information
npm ERR! gyp info spawn C:\Python312\python.exe
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   'C:\\Users\\xiaokeai\\AppData\\Roaming\\npm\\node_modules\\@tableau\\taco-toolkit\\node_modules\\node-gyp\\gyp\\gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'msvs',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\xiaokeai\\AppData\\Roaming\\npm\\node_modules\\@tableau\\taco-toolkit\\node_modules\\isolated-vm\\build\\config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\xiaokeai\\AppData\\Roaming\\npm\\node_modules\\@tableau\\taco-toolkit\\node_modules\\node-gyp\\addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\xiaokeai\\AppData\\Local\\node-gyp\\Cache\\18.19.0\\include\\node\\common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=C:\\Users\\xiaokeai\\AppData\\Local\\node-gyp\\Cache\\18.19.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\xiaokeai\\AppData\\Roaming\\npm\\node_modules\\@tableau\\taco-toolkit\\node_modules\\node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\xiaokeai\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\18.19.0\\\\<(target_arch)\\\\node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\xiaokeai\\AppData\\Roaming\\npm\\node_modules\\@tableau\\taco-toolkit\\node_modules\\isolated-vm',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'C:\\Users\\xiaokeai\\AppData\\Roaming\\npm\\node_modules\\@tableau\\taco-toolkit\\node_modules\\isolated-vm\\build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! Traceback (most recent call last):
npm ERR!   File "C:\Users\xiaokeai\AppData\Roaming\npm\node_modules\@tableau\taco-toolkit\node_modules\node-gyp\gyp\gyp_main.py", line 42, in <module>
npm ERR!     import gyp  # noqa: E402
npm ERR!     ^^^^^^^^^^
npm ERR!   File "C:\Users\xiaokeai\AppData\Roaming\npm\node_modules\@tableau\taco-toolkit\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 9, in <module>
npm ERR!     import gyp.input
npm ERR!   File "C:\Users\xiaokeai\AppData\Roaming\npm\node_modules\@tableau\taco-toolkit\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 19, in <module>
npm ERR!     from distutils.version import StrictVersion
npm ERR! ModuleNotFoundError: No module named 'distutils'
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\xiaokeai\AppData\Roaming\npm\node_modules\@tableau\taco-toolkit\node_modules\node-gyp\lib\configure.js:325:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:517:28)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:292:12)
npm ERR! gyp ERR! System Windows_NT 10.0.22621
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\xiaokeai\\AppData\\Roaming\\npm\\node_modules\\@tableau\\taco-toolkit\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--release" "-j" "4"
npm ERR! gyp ERR! cwd C:\Users\xiaokeai\AppData\Roaming\npm\node_modules\@tableau\taco-toolkit\node_modules\isolated-vm
npm ERR! gyp ERR! node -v v18.19.0
npm ERR! gyp ERR! node-gyp -v v9.4.0
npm ERR! gyp ERR! not ok

------------
i have try the version of nodejs 16,18,20, but the result is very very sad, the error always exist, who can help me ?

**Comment by lexara-prime-ai** [comment]
@duniang818 I had the same issue when I first tried to install `taco-toolkit`. In my case, upgrading the `npm` version resolved the issue.
